### Studi Kasus Implementasi Klasifikasi Teks pada NLP: Sentimen Analisis Review APK Play Store

Sentimen Analisis Review APK Play Store adalah proses menganalisis dan mengevaluasi sentimen atau perasaan yang diungkapkan oleh pengguna dalam ulasan atau review mereka di Play Store, platform distribusi aplikasi Android resmi dari Google. 

Tujuannya adalah memahami bahwa ulasan-ulasan tersebut cenderung sangatpositif, positif, negatif, atau netral terhadap suatu aplikasi. 

saya akan menggunakan studi kasus Sentimen Analisis pada Aplikasi Tokopedia

In [1]:
import nltk
import csv
import requests
from io import StringIO
import re
import string
import pandas as pd
import numpy as np
import datetime as dt
import seaborn as sns
pd.options.mode.chained_assignment = None
seed = 0
np.random.seed(seed)
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from wordcloud import WordCloud
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from sklearn.feature_extraction.text import TfidfVectorizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Embedding, LSTM, Bidirectional
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
#Mendownload yang diperlukan untuk tokenisasi teks serta Mendownload dataset yang berisi daftar kata-kata berhenti (stopwords) dalam berbagai bahasa.
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\TUF
[nltk_data]     GAMING\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\TUF
[nltk_data]     GAMING\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
app_reviews_df = pd.read_csv('ulasan_aplikasi.csv')

In [4]:
app_reviews_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,a801cb94-be3d-459b-9faa-ccb04fe97709,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"pantes kalian hampir bangkrut, cara kalian men...",1,269,3.304.0,2025-03-20 23:14:43,"Halo Toppers, terima kasih atas rating yang ka...",2025-03-20 23:47:04,3.304.0
1,7d64cae4-117d-4421-96a2-6bc33b49e7da,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,bisa g sih ubah kurir rekomendasi berdasarkan ...,2,23,3.305.0,2025-04-05 15:01:00,"Halo Toppers, terima kasih atas rating yang ka...",2025-04-05 15:20:06,3.305.0
2,82ab6537-5c22-4c9c-8c19-00f52a4c3612,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Makin kesini, makin nggak nyaman belanja di To...",2,0,3.304.0,2025-03-24 14:45:56,"Halo Toppers, terima kasih atas rating yang ka...",2025-03-24 15:07:01,3.304.0
3,9faf326c-e252-468c-b283-19ea0bac9f3c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Setelah di beli tiktok, tokopedia jadi ancur, ...",1,28,3.305.0,2025-04-05 02:13:01,"Halo Toppers, terima kasih atas rating yang ka...",2025-04-05 02:47:03,3.305.0
4,48aa873e-07a2-42e9-ad97-8717f8efba37,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,4 & 5 April 2025 mendadak fitur pencarian di a...,1,11,3.305.0,2025-04-05 05:49:36,"Halo Toppers, terima kasih atas rating yang ka...",2025-04-05 06:07:08,3.305.0

In [5]:
#Menampilkan informasi tentang Dataframe app_reviews_df
app_reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76500 entries, 0 to 76499
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              76500 non-null  object
 1   userName              76500 non-null  object
 2   userImage             76500 non-null  object
 3   content               76500 non-null  object
 4   score                 76500 non-null  int64
 5   thumbsUpCount         76500 non-null  int64
 6   reviewCreatedVersion  55074 non-null  object
 7   at                    76500 non-null  object
 8   replyContent          46257 non-null  object
 9   repliedAt             46257 non-null  object
 10  appVersion            55074 non-null  object
dtypes: int64(2), object(9)
memory usage: 6.4+ MB

In [6]:
# membuat Dataframe baru (clean_df) dengan menghapus baris yang memiliki nilai yang hilang (NaN) dari app_reviews_df
clean_df = app_reviews_df.dropna()

In [7]:
# menghapus baris duplikat dari Dataframe clean_df
clean_df = clean_df.drop_duplicates()

# Menghitung jumlah baris dan kolom dalam Dataframe clean_df setelah menghapus duplikat
jumlah_ulasan_setelah_hapus_duplikat, jumlah_kolom_setelah_hapus_duplickat = clean_df.shape

In [8]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36408 entries, 0 to 76498
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              36408 non-null  object
 1   userName              36408 non-null  object
 2   userImage             36408 non-null  object
 3   content               36408 non-null  object
 4   score                 36408 non-null  int64
 5   thumbsUpCount         36408 non-null  int64
 6   reviewCreatedVersion  36408 non-null  object
 7   at                    36408 non-null  object
 8   replyContent          36408 non-null  object
 9   repliedAt             36408 non-null  object
 10  appVersion            36408 non-null  object
dtypes: int64(2), object(9)
memory usage: 3.3+ MB

#### Data Preprocessing

In [ ]:
# Membuat Fungsi cleaningText untuk membersihkan teks dari karakter-karakter yag tidak diperlukan
def cleaningText(text):
    text = re.sub(r'@[A-Za-z0-9]+', '', text) # menghapus mention
    text = re.sub(r'#[A-Za-z0-9]+', '', text) # menghapus hashtag
    text = re.sub(r'RT[\s]', '', text) # menghapus RT
    text = re.sub(r"http\S+", '', text) # menghapus link
    text = re.sub(r'[0-9]+', '', text) # menghapus angka
    text = re.sub(r'[^\w\s]', '', text) # menghapus karakter selain huruf dan angka
    text = text.replace('\n', ' ') # mengganti baris baru dengan spasi
    text = text.translate(str.maketrans('', '', string.punctuation)) # menghapus semua tanda baca
    text = text.strip(' ') # menghapus karakter spasi dari kiri dan kanan teks
    return text

In [ ]:
# Membuat Fungsi casefoldingText() untuk Mengubah semua karakter dalam teks menjadi huruf kecil
def casefoldingText(text): # Mengubah semua karakter dalam teks menjadi huruf kecil
    text = text.lower()
    return text

In [11]:
# Memecah atau membagi string, teks menjadi daftar token
def tokenizingText(text): 
    text = word_tokenize(text)
    return text

In [12]:
# Menghapus stopwords dalam teks
def filteringText(text): # Menghapus stopwords dalam teks
    listStopwords = set(stopwords.words('indonesian'))
    listStopwords1 = set(stopwords.words('english'))
    listStopwords.update(listStopwords1)
    listStopwords.update(['iya','yaa','gak','nya','na','sih','ku',"di","ga","ya","gaa","loh","kah","woi","woii","woy"])
    filtered = []
    for txt in text:
        if txt not in listStopwords:
            filtered.append(txt)
    text = filtered
    return text

In [ ]:
# Membuat fungsi stemmingText() untuk Mengurangi kata ke bentuk dasarnya yang menghilangkan imbuhan awalan dan akhiran atau ke akar kata
def stemmingText(text): 
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
 
    # Memecah teks menjadi daftar kata
    words = text.split()
 
    # Menerapkan stemming pada setiap kata dalam daftar
    stemmed_words = [stemmer.stem(word) for word in words]
 
    # Menggabungkan kata-kata yang telah distem
    stemmed_text = ' '.join(stemmed_words)
 
    return stemmed_text

In [ ]:
# Membuat fungsi toSentence() untuk mengubah daftar kata menjadi kalimat
def toSentence(list_words):
    sentence = ' '.join(word for word in list_words)
    return sentence

In [ ]:
# Membuat fungsi fix_slangwords() untuk membersihkan data teks, khususnya mengganti kata-kata slang (gaul, singkatan, atau tidak baku) menjadi bentuk baku atau asli.
slangwords = {"@": "di", "abis": "habis", "wtb": "beli", "masi": "masih", "wts": "jual", "wtt": "tukar", "bgt": "banget", "maks": "maksimal"}
def fix_slangwords(text):
    words = text.split()
    fixed_words = []
 
    for word in words:
        if word.lower() in slangwords:
            fixed_words.append(slangwords[word.lower()])
        else:
            fixed_words.append(word)
 
    fixed_text = ' '.join(fixed_words)
    return fixed_text

Setelah semua langkah preprocessing telah ditetapkan, langkah berikutnya adalah menerapkannya.

In [16]:
#Membersihkan teks dan menyimpannya dikolom 'text_clean'
clean_df['text_clean'] = clean_df['content'].apply(cleaningText)

#Mengubah huruf dalam teks menjadi huruf kecil dan menyimpannya di 'text_caseFoldingText'
clean_df['text_casefoldingText'] = clean_df['text_clean'].apply(casefoldingText)

#Mengganti kata-kata slang dengan kata-kata standar dan menyimpannya di 'text_slangwords'
clean_df['text_slangwords'] = clean_df['text_casefoldingText'].apply(fix_slangwords)

#Memecah teks menjadi token (kata-kata) dan menyimpannya di 'text_tokenizingText'
clean_df['text_tokenizingText'] = clean_df['text_slangwords'].apply(tokenizingText)

#Menghapus kata-kata stop (kata-kata umum) dan menyimpannya di 'text_stopword'
clean_df['text_stopWord'] = clean_df['text_tokenizingText'].apply(filteringText)

#Menggabungkan token-token menjadi kalimat dan mennyimpannya di 'text_akhir'
clean_df['text_akhir'] = clean_df['text_stopWord'].apply(toSentence)

In [ ]:
#Menampilkan Hasil
clean_df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,text_clean,text_casefoldingText,text_slangwords,text_tokenizingText,text_stopWord,text_akhir
0,a801cb94-be3d-459b-9faa-ccb04fe97709,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"pantes kalian hampir bangkrut, cara kalian men...",1,269,3.304.0,2025-03-20 23:14:43,"Halo Toppers, terima kasih atas rating yang ka...",2025-03-20 23:47:04,3.304.0,pantes kalian hampir bangkrut cara kalian mena...,pantes kalian hampir bangkrut cara kalian mena...,pantes kalian hampir bangkrut cara kalian mena...,"[pantes, kalian, hampir, bangkrut, cara, kalia...","[pantes, bangkrut, menangani, barang, hilang, ...",pantes bangkrut menangani barang hilang sebene...
1,7d64cae4-117d-4421-96a2-6bc33b49e7da,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,bisa g sih ubah kurir rekomendasi berdasarkan ...,2,23,3.305.0,2025-04-05 15:01:00,"Halo Toppers, terima kasih atas rating yang ka...",2025-04-05 15:20:06,3.305.0,bisa g sih ubah kurir rekomendasi berdasarkan ...,bisa g sih ubah kurir rekomendasi berdasarkan ...,bisa g sih ubah kurir rekomendasi berdasarkan ...,"[bisa, g, sih, ubah, kurir, rekomendasi, berda...","[g, ubah, kurir, rekomendasi, berdasarkan, pen...",g ubah kurir rekomendasi berdasarkan pengalama...
2,82ab6537-5c22-4c9c-8c19-00f52a4c3612,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Makin kesini, makin nggak nyaman belanja di To...",2,0,3.304.0,2025-03-24 14:45:56,"Halo Toppers, terima kasih atas rating yang ka...",2025-03-24 15:07:01,3.304.0,Makin kesini makin nggak nyaman belanja di Tok...,makin kesini makin nggak nyaman belanja di tok...,makin kesini makin nggak nyaman belanja di tok...,"[makin, kesini, makin, nggak, nyaman, belanja,...","[kesini, nggak, nyaman, belanja, tokopedia, sa...",kesini nggak nyaman belanja tokopedia saran gw...
3,9faf326c-e252-468c-b283-19ea0bac9f3c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Setelah di beli tiktok, tokopedia jadi ancur, ...",1,28,3.305.0,2025-04-05 02:13:01,"Halo Toppers, terima kasih atas rating yang ka...",2025-04-05 02:47:03,3.305.0,Setelah di beli tiktok tokopedia jadi ancur pa...,setelah di beli tiktok tokopedia jadi ancur pa...,setelah di beli tiktok tokopedia jadi ancur pa...,"[setelah, di, beli, tiktok, tokopedia, jadi, a...","[beli, tiktok, tokopedia, ancur, pantes, aja, ...",beli tiktok tokopedia ancur pantes aja toko sy...
4,48aa873e-07a2-42e9-ad97-8717f8efba37,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,4 & 5 April 2025 mendadak fitur pencarian di a...,1,11,3.305.0,2025-04-05 05:49:36,"Halo Toppers, terima kasih atas rating yang ka...",2025-04-05 06:07:08,3.305.0,April mendadak fitur pencarian di aplikasi ti...,april mendadak fitur pencarian di aplikasi ti...,april mendadak fitur pencarian di aplikasi tid...,"[april, mendadak, fitur, pencarian, di, aplika...","[april, mendadak, fitur, pencarian, aplikasi, ...",april mendadak fitur pencarian aplikasi mencar...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76489,ecf4b609-f375-4c7c-8549-8dcd44d88d98,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Ada promo muncul 50% ga bisa d pakai.. tolong ...,1,0,3.281.0,2024-09-22 19:45:36,"Halo Toppers, terima kasih atas rating yang ka...",2024-09-22 20:20:11,3.281.0,Ada promo muncul ga bisa d pakai tolong lah y...,ada promo muncul ga bisa d pakai tolong lah y...,ada promo muncul ga bisa d pakai tolong lah yg...,"[ada, promo, muncul, ga, bisa, d, pakai, tolon...","[promo, muncul, pakai, tolong, yg, pakai, aja,...",promo muncul pakai tolong yg pakai aja munculi...
76491,19f203cb-da4f-4e8b-a21b-b2583ae4067d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Parah jangan instal aplikasi ini, saya sangat ...",1,1,3.113,2021-02-12 21:41:16,"Hai Kak Aidin, Mohon maaf atas transaksinya ya...",2021-02-12 22:07:51,3.113,Parah jangan instal aplikasi ini saya sangat d...,parah jangan instal aplikasi ini saya sangat d...,parah jangan instal aplikasi ini saya sangat d...,"[parah, jangan, instal, aplikasi, ini, saya, s...","[parah, instal, aplikasi, dirugikan, belanja, ...",parah instal aplikasi dirugikan belanja barang...
76494,6bef50d7-2197-4b6f-8d7d-1ded6551f58a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sangat membantu untuk membeli pelatihan.. dan ...,5,16,3.232,2023-09-02 22:44:44,"Toppers, terima kasih atas rating yang kamu be...",2023-09-02 22:50:03,3.232,sangat membantu untuk membeli pelatihan dan sa...,sangat membantu untuk membeli pelatihan dan sa...,sangat membantu untuk membeli pelatihan dan sa...,"[sangat, membantu, untuk, membeli, pelatihan, ...","[membantu, membeli, pelatihan, membantu, menam...",membantu membeli pelatihan membantu menambah i...
76495,a3aae24a-70ea-4727-b99b-b4d49dc0661f,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Barang nya pas dengan yang di posting Dan kiri...,5,0,3.54,2019-12-10 19:15:11,"Hai Febrian, terima kasih atas dukungan dan ke...",2020-01-05 15:21:58,3.54,Barang nya pas dengan yang di posting Dan kiri...,barang nya pas dengan yang di posting dan kiri...,barang nya pas dengan yang di posting dan kiri...,"[barang, nya, pas, dengan, yang, di, posting, ...","[barang, pas, posting, kiriman, cepat, suka, b...",barang pas posting kiriman cepat suka belanja ...
76498,f8c2db55-4c98-4839-a886-fb873fae74c8,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Gimana sih apk gambarnya gak kebuka juga giman...,2,0,3.9,2018-12-06 11:02:41,"Hai Toppers, mohon maaf atas kendalanya, terka...",2018-12-06 12:20:45,3.9,Gimana sih apk gambarnya gak kebuka juga giman...,gimana sih apk gambarnya gak kebuka juga giman...,gimana sih apk gambarnya gak kebuka juga giman...,"[gimana, sih, apk, gambarnya, gak, kebuka, jug...","[gimana, apk, gambarnya, kebuka, gimana, belan...",gimana apk gambarnya kebuka gimana belanja tok...

In [18]:
#Membaca data kamus kata-kata positif dari github
lexicon_positive = dict()

response = requests.get('https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_positive.csv')
# Mengirim permintaan HTTP untuk mendapatkan file CSV dari Gitub

if response.status_code == 200:
    #jika permintaan berhasil
    reader = csv.reader(StringIO(response.text), delimiter=',')
    #membaca teks respons sebagai file CSV menggunakan pembaca CSV dengan pemisah koma

    for row in reader:
        #Mengulangi setiap baris dalam file CSV
        lexicon_positive[row[0]] = int(row[1])
        #Menambahkan kata-kata positif dan skornya kedalam kamus lexicon_positive
else:
    print("Failed to fetch positive Lexicon Data")


#membaca data kamus kata-kata negatif dari github
lexicon_negative = dict()

response = requests.get('https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_negative.csv')
# Mengirim permintaan HTTP untuk mendapatkan file CSV dari Gitub

if response.status_code == 200:
    #jika permintaan berhasil
    reader = csv.reader(StringIO(response.text), delimiter=',')
    #membaca teks respons sebagai file CSV menggunakan pembaca CSV dengan pemisah koma

    for row in reader:
        #Mengulangi setiap baris dalam file CSV
        lexicon_negative[row[0]] = int(row[1])
        #Menambahkan kata-kata negatif dan skornya kedalam kamus lexicon_negative
else:
    print("Failed to fetch negative Lexicon Data")

In [ ]:
# Fungsi untuk menentukan polaritas sentimen
def sentiment_analysis_lexicon_indonesia(text):
 
    score = 0
 
    for word in text:
        if (word in lexicon_positive):
            score = score + lexicon_positive[word]
    for word in text:
        if (word in lexicon_negative):
            score = score + lexicon_negative[word]


    polarity = ''

    if score == 5:
        polarity = 'sangat_positive'
    elif score == 4:
        polarity = 'positive'
    elif score == 3:
        polarity = 'netral'
    else:
        polarity = 'negative'# Sentimen negatif (1 atau 2)

    return score, polarity

In [20]:
results = clean_df['text_stopWord'].apply(sentiment_analysis_lexicon_indonesia)
results = list(zip(*results))
clean_df['polarity_score'] = results[0]
clean_df['polarity'] = results[1]
print(clean_df['polarity'].value_counts())

polarity
negative           31605
netral              1871
positive            1519
sangat_positive     1413
Name: count, dtype: int64

#### Ekstraksi Fitur dengan TF-IDF dan Data Splitting

Setelah berhasil menetapkan label untuk setiap entri dalam dataset, kita akan menggunakan metode ekstraksi fitur yang disebut TF-IDF.

In [21]:
#Pisahkan data menjadi fitur (tweet) dan label (sentiment)
X = clean_df['text_akhir']
y = clean_df['polarity']

In [ ]:
#Ekstraksi Fitur dengan TF-IDF
tfidf = TfidfVectorizer(max_features=200, min_df=17, max_df=0.8)
X_tfidf = tfidf.fit_transform(X)

In [23]:
#Konversi hasil ekstraksi fitur menjadi DataFrame
features_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())

#Menampilkan hasil Ekstraksi fitur
features_df

,admin,aja,akun,alamat,alasan,aneh,apk,aplikasi,aplikasinya,app,...,transaksi,trus,uang,udah,udh,ulasan,update,utk,voucher,yg
0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
1,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
2,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.556542,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
3,0.0,0.253540,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.176399,0.0,0.0,0.0,0.0,0.102832
4,0.0,0.000000,0.0,0.0,0.000000,0.229206,0.000000,0.256610,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.355335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36403,0.0,0.265117,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.215054
36404,0.0,0.000000,0.0,0.0,0.407842,0.000000,0.000000,0.231379,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
36405,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
36406,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
36407,0.0,0.224406,0.0,0.0,0.000000,0.000000,0.314295,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.182031

In [ ]:
#Membagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

#### Modeling

##### Modeling with Logistik Regression

In [ ]:
# Membuat objek model Logistic Regression
logistic_regression = LogisticRegression()
 
# Menampilkan distribusi kelas di y_train dan y_test
print("Class distribution in y_train:")
print(y_train.value_counts())
print("\nClass distribution in y_test:")
print(y_test.value_counts())


y_train_decoded = y_train
y_test_decoded = y_test

# Memastikan ada setidaknya dua kelas dalam data
if len(np.unique(y_train_decoded)) < 2:
	raise ValueError("The dataset contains only one class. Please ensure the dataset has at least two classes for classification.")

# Melatih model Logistic Regression pada data pelatihan
logistic_regression.fit(X_train, y_train_decoded)
 
# Prediksi sentimen pada data pelatihan dan data uji
y_pred_train_lr = logistic_regression.predict(X_train)
y_pred_test_lr = logistic_regression.predict(X_test)
 
# Evaluasi akurasi model Logistic Regression pada data pelatihan
accuracy_train_lr = accuracy_score(y_pred_train_lr, y_train_decoded)
 
# Evaluasi akurasi model Logistic Regression pada data uji
accuracy_test_lr = accuracy_score(y_pred_test_lr, y_test_decoded)

Class distribution in y_train:
polarity
negative           25276
netral              1506
positive            1212
sangat_positive     1132
Name: count, dtype: int64

Class distribution in y_test:
polarity
negative           6329
netral              365
positive            307
sangat_positive     281
Name: count, dtype: int64

##### Evaluasi Model

In [26]:
# Menampilkan akurasi
print('Logistic Regression - accuracy_train:', accuracy_train_lr)
print('Logistic Regression - accuracy_test:', accuracy_test_lr)

Logistic Regression - accuracy_train: 0.8678156973151137
Logistic Regression - accuracy_test: 0.869129360065916

In [ ]:
# # Encode label (y) menjadi numerik
# label_encoder = LabelEncoder()
# y_encoded = label_encoder.fit_transform(y)

# # Konversi label menjadi one-hot encoding
# y_one_hot = to_categorical(y_encoded)

# # Bagi data menjadi data latih dan data uji
# X_train, X_test, y_train, y_test = train_test_split(X_tfidf.toarray(), y_one_hot, test_size=0.2, random_state=seed)

# # Membuat model Sequential
# model = Sequential()

# # Menambahkan lapisan input dan embedding
# model.add(Dense(128, input_shape=(X_train.shape[1],), activation='relu'))

# # Menambahkan lapisan hidden
# model.add(Dropout(0.5))
# model.add(Dense(64, activation='relu'))

# # Menambahkan lapisan output
# model.add(Dense(y_train.shape[1], activation='softmax'))

# # Kompilasi model
# model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# # Melatih model
# history = model.fit(X_train, y_train, epochs=10, batch_size=128, validation_data=(X_test, y_test))

# # Evaluasi model
# loss, accuracy = model.evaluate(X_test, y_test)
# print(f"Test Accuracy: {accuracy}")

Epoch 1/10

c:\Users\TUF GAMING\.conda\envs\verzha_new\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

228/228 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8367 - loss: 0.7330 - val_accuracy: 0.8669 - val_loss: 0.5104
Epoch 2/10
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.5186 - val_accuracy: 0.8669 - val_loss: 0.5067
Epoch 3/10
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8662 - loss: 0.5055 - val_accuracy: 0.8669 - val_loss: 0.5039
Epoch 4/10
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8673 - loss: 0.5019 - val_accuracy: 0.8669 - val_loss: 0.5032
Epoch 5/10
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8678 - loss: 0.4913 - val_accuracy: 0.8669 - val_loss: 0.5009
Epoch 6/10
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8668 - loss: 0.4905 - val_accuracy: 0.8669 - val_loss: 0.5001
Epoch 7/10
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8670 - loss: 0.4843 - val_accuracy: 0.8669 - val_loss: 0.4995
Epoch 8/10
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8701 - loss: 0.4686 - val_accuracy: 0.8669 - val_loss: 0.5005
Epoch 9/10
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8671 - loss: 0.4741 - val_accuracy: 0.8669 - val_loss: 0.5036
Epoch 10/10
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8702 - loss: 0.4664 - val_accuracy: 0.8672 - val_loss: 0.5006
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.8642 - loss: 0.5077
Test Accuracy: 0.8672068119049072